# Generated by Django 5.2.14 on 2026-05-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=500, verbose_name='原始文件名')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('summary', models.TextField(blank=True, default='', verbose_name='AI 总结')),
                ('mapped_points', models.JSONField(blank=True, default=list, verbose_name='映射知识点')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '上传任务',
                'verbose_name_plural': '上传任务',
                'db_table': 'upload_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
